api_url: "https://microcks.gin.dev.securingsam.io/rest/Reputation+API/1.0.0/domain/ranking/{}"
auth_token: "I_am_under_stress_when_I_test"

influxdb:
  url: "http://localhost:8086"
  token: "your_influxdb_token"
  org: "your_org_name"
  bucket: "stress_test_bucket"
